### ISSUE TITLE
Not able to share bookmark

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#94] opened 2019-07-22 17:24 UTC
Hello,

By reviewing dx_ctl_js_bookmarks binary, there is no option to share a bookmark, would it be possible to add it as an option there?

Thanks in advance and regards

**Comment by pioro** [comment] 2019-07-22 17:26
Hello,

It's duplicate of issue no 83.
I will add it in next release.

**Comment by pioro** [comment] 2019-08-28 14:42
pushed into dev

**Closed by pioro** 2019-08-28 14:42 UTC
Labels: enhancement
